import type { Metadata } from "next";

export const viewport = {
  initialSacale: 1.0,
  width:"device-width",
  colorScheme:'dark',
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
        {children}
      </body>
    </html>
  );
}
