import Cabecalho from "@/components/Cabecalho/Cabecalho";
import Rodape from "@/components/Rodape/Rodape";
import type { Metadata } from "next";

export const viewport = {
  initialSacale: 1.0,
  width:"device-width",
  colorScheme:'dark',
};

export const metadata: Metadata = {
  title: "Worlds in Collision",
  description: "Generated by Ana Carolina, Mateus, Gabriela",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
        <Cabecalho />
        {children}
        <Rodape/>
      </body>
    </html>
  );
}
